server:
  port: 9090
spring:
  rabbitmq:
    username: daniel
    password: daniel
    virtual-host: /
    host: 192.168.0.200
    port: 5672
    #监听
    listener:
      simple:
        retry:
          enabled: true #开启重试，默认不开启
          max-attempts: 3 #最大重试次数
          initial-interval: 1000ms #重试间隔时间（单位毫秒）
          max-interval: 1200000ms #重试最大时间间隔（单位毫秒）
          # 乘子。间隔时间*乘子=下一次的间隔时间，不能超过 max-interval
          # 以本处为例：第一次间隔 5 秒，第二次间隔 10 秒，以此类推
          multiplier: 2
    #发送
    publisher-confirm-type: correlated
    publisher-returns: true
logging:
  config: classpath:logback.xml
  level:
    root: info
    cn.sxgan.db.mapper: debug