spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.88.252:3306/zoey_mock_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: daniel
    password: ZOEY_ENC(QySWSq23aHbKZZYJnT13FzCtyAWKMHxa)
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置
    druid:
      # 配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      # CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      # 最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      # 可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  data:
    redis:
      #  host: 127.0.0.1
      host: 114.116.88.252
      database: 1
      port: 6379
      password: daniel
      jedis:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: -1ms
      connect-timeout: 30000ms

# spring集成Mybatis环境
mybatis-plus:
  # pojo别名扫描包
  type-aliases-package: cn.sxgan.common.entity
  # 加载Mybatis映射文件
  mapper-locations: classpath:mappers/*Mapper.xml
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 只打印sql不打印结果集
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl